swagger: '2.0'
info:
  title: Security API
  version: 1.0.0
basePath: /api
tags:
  - name: auth
    description: Operations about authentication
schemes:
  - http
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Logs user into the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  ApiResponse:
    type: object
    properties:
      message:
        type: string
  User:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      email:
        type: string
